services:
  # Proposers
  proposer-1:
    build:
      context: .
      dockerfile: ./proposer/Dockerfile
    environment:
      - NODE_ID=1
      - DEBUG=true
      - DEBUG_LEVEL=trace
    volumes:
      - ./data/proposer-1:/data
    ports:
      - "8001:8080"
    networks:
      - paxos-network

  proposer-2:
    build:
      context: .
      dockerfile: ./proposer/Dockerfile
    environment:
      - NODE_ID=2
      - DEBUG=true
      - DEBUG_LEVEL=trace
    volumes:
      - ./data/proposer-2:/data
    ports:
      - "8002:8080"
    networks:
      - paxos-network

  proposer-3:
    build:
      context: .
      dockerfile: ./proposer/Dockerfile
    environment:
      - NODE_ID=3
      - DEBUG=true
      - DEBUG_LEVEL=trace
    volumes:
      - ./data/proposer-3:/data
    ports:
      - "8003:8080"
    networks:
      - paxos-network

  proposer-4:
    build:
      context: .
      dockerfile: ./proposer/Dockerfile
    environment:
      - NODE_ID=4
      - DEBUG=true
      - DEBUG_LEVEL=trace
    volumes:
      - ./data/proposer-4:/data
    ports:
      - "8004:8080"
    networks:
      - paxos-network

  proposer-5:
    build:
      context: .
      dockerfile: ./proposer/Dockerfile
    environment:
      - NODE_ID=5
      - DEBUG=true
      - DEBUG_LEVEL=trace
    volumes:
      - ./data/proposer-5:/data
    ports:
      - "8005:8080"
    networks:
      - paxos-network

  # Acceptors
  acceptor-1:
    build:
      context: .
      dockerfile: ./acceptor/Dockerfile
    environment:
      - NODE_ID=1
      - DEBUG=true
      - DEBUG_LEVEL=trace
    volumes:
      - ./data/acceptor-1:/data
    ports:
      - "8101:8080"
    networks:
      - paxos-network

  acceptor-2:
    build:
      context: .
      dockerfile: ./acceptor/Dockerfile
    environment:
      - NODE_ID=2
      - DEBUG=true
      - DEBUG_LEVEL=trace
    volumes:
      - ./data/acceptor-2:/data
    ports:
      - "8102:8080"
    networks:
      - paxos-network

  acceptor-3:
    build:
      context: .
      dockerfile: ./acceptor/Dockerfile
    environment:
      - NODE_ID=3
      - DEBUG=true
      - DEBUG_LEVEL=trace
    volumes:
      - ./data/acceptor-3:/data
    ports:
      - "8103:8080"
    networks:
      - paxos-network

  acceptor-4:
    build:
      context: .
      dockerfile: ./acceptor/Dockerfile
    environment:
      - NODE_ID=4
      - DEBUG=true
      - DEBUG_LEVEL=trace
    volumes:
      - ./data/acceptor-4:/data
    ports:
      - "8104:8080"
    networks:
      - paxos-network

  acceptor-5:
    build:
      context: .
      dockerfile: ./acceptor/Dockerfile
    environment:
      - NODE_ID=5
      - DEBUG=true
      - DEBUG_LEVEL=trace
    volumes:
      - ./data/acceptor-5:/data
    ports:
      - "8105:8080"
    networks:
      - paxos-network

  # Learners
  learner-1:
    build:
      context: .
      dockerfile: ./learner/Dockerfile
    environment:
      - NODE_ID=1
      - DEBUG=true
      - DEBUG_LEVEL=trace
      - USE_CLUSTER_STORE=true
    volumes:
      - ./data/learner-1:/data
    ports:
      - "8201:8080"
    networks:
      - paxos-network

  learner-2:
    build:
      context: .
      dockerfile: ./learner/Dockerfile
    environment:
      - NODE_ID=2
      - DEBUG=true
      - DEBUG_LEVEL=trace
      - USE_CLUSTER_STORE=true
    volumes:
      - ./data/learner-2:/data
    ports:
      - "8202:8080"
    networks:
      - paxos-network

  # Cluster Store
  cluster-store-1:
    build:
      context: .
      dockerfile: ./cluster_store/Dockerfile
    environment:
      - NODE_ID=1
      - DEBUG=true
      - DEBUG_LEVEL=trace
      - STORES=cluster-store-1:8080,cluster-store-2:8080,cluster-store-3:8080
    volumes:
      - ./data/cluster-store-1:/data
    ports:
      - "8301:8080"
    networks:
      - paxos-network

  cluster-store-2:
    build:
      context: .
      dockerfile: ./cluster_store/Dockerfile
    environment:
      - NODE_ID=2
      - DEBUG=true
      - DEBUG_LEVEL=trace
      - STORES=cluster-store-1:8080,cluster-store-2:8080,cluster-store-3:8080
    volumes:
      - ./data/cluster-store-2:/data
    ports:
      - "8302:8080"
    networks:
      - paxos-network

  cluster-store-3:
    build:
      context: .
      dockerfile: ./cluster_store/Dockerfile
    environment:
      - NODE_ID=3
      - DEBUG=true
      - DEBUG_LEVEL=trace
      - STORES=cluster-store-1:8080,cluster-store-2:8080,cluster-store-3:8080
    volumes:
      - ./data/cluster-store-3:/data
    ports:
      - "8303:8080"
    networks:
      - paxos-network

  # Clients
  client-1:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    environment:
      - CLIENT_ID=client-1
      - NODE_ID=1
      - DEBUG=true
      - DEBUG_LEVEL=trace
      - PROPOSER=proposer-1:8080
      - NUM_OPERATIONS=20
      - AUTO_START=true
    volumes:
      - ./data/client-1:/data
    ports:
      - "8401:8080"
      - "8501:8081"
    networks:
      - paxos-network

  client-2:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    environment:
      - CLIENT_ID=client-2
      - NODE_ID=2
      - DEBUG=true
      - DEBUG_LEVEL=trace
      - PROPOSER=proposer-2:8080
      - NUM_OPERATIONS=20
      - AUTO_START=true
    volumes:
      - ./data/client-2:/data
    ports:
      - "8402:8080"
      - "8502:8081"
    networks:
      - paxos-network

  client-3:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    environment:
      - CLIENT_ID=client-3
      - NODE_ID=3
      - DEBUG=true
      - DEBUG_LEVEL=trace
      - PROPOSER=proposer-3:8080
      - NUM_OPERATIONS=20
      - AUTO_START=true
    volumes:
      - ./data/client-3:/data
    ports:
      - "8403:8080"
      - "8503:8081"
    networks:
      - paxos-network

  client-4:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    environment:
      - CLIENT_ID=client-4
      - NODE_ID=4
      - DEBUG=true
      - DEBUG_LEVEL=trace
      - PROPOSER=proposer-4:8080
      - NUM_OPERATIONS=20
      - AUTO_START=true
    volumes:
      - ./data/client-4:/data
    ports:
      - "8404:8080"
      - "8504:8081"
    networks:
      - paxos-network

  client-5:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    environment:
      - CLIENT_ID=client-5
      - NODE_ID=5
      - DEBUG=true
      - DEBUG_LEVEL=trace
      - PROPOSER=proposer-5:8080
      - NUM_OPERATIONS=20
      - AUTO_START=true
    volumes:
      - ./data/client-5:/data
    ports:
      - "8405:8080"
      - "8505:8081"
    networks:
      - paxos-network

networks:
  paxos-network:
    driver: bridge