services:
  # Proposers (Cluster Sync)
  proposer1:
    build:
      context: .
      dockerfile: proposer/Dockerfile
    environment:
      - DEBUG=${DEBUG:-false}
      - PROPOSER_ID=proposer_1
      - ACCEPTORS=http://acceptor1:8100,http://acceptor2:8100,http://acceptor3:8100,http://acceptor4:8100,http://acceptor5:8100
      - LEARNERS=http://learner1:8200,http://learner2:8200
      - STORES=http://store1:8300,http://store2:8300,http://store3:8300
      - PROPOSERS=http://proposer1:8000,http://proposer2:8000,http://proposer3:8000,http://proposer4:8000,http://proposer5:8000
    ports:
      - "8001:8000"
    volumes:
      - ./logs:/app/logs
    networks:
      - paxos-network

  proposer2:
    build:
      context: .
      dockerfile: proposer/Dockerfile
    environment:
      - DEBUG=${DEBUG:-false}
      - PROPOSER_ID=proposer_2
      - ACCEPTORS=http://acceptor1:8100,http://acceptor2:8100,http://acceptor3:8100,http://acceptor4:8100,http://acceptor5:8100
      - LEARNERS=http://learner1:8200,http://learner2:8200
      - STORES=http://store1:8300,http://store2:8300,http://store3:8300
      - PROPOSERS=http://proposer1:8000,http://proposer2:8000,http://proposer3:8000,http://proposer4:8000,http://proposer5:8000
    ports:
      - "8002:8000"
    volumes:
      - ./logs:/app/logs
    networks:
      - paxos-network

  proposer3:
    build:
      context: .
      dockerfile: proposer/Dockerfile
    environment:
      - DEBUG=${DEBUG:-false}
      - PROPOSER_ID=proposer_3
      - ACCEPTORS=http://acceptor1:8100,http://acceptor2:8100,http://acceptor3:8100,http://acceptor4:8100,http://acceptor5:8100
      - LEARNERS=http://learner1:8200,http://learner2:8200
      - STORES=http://store1:8300,http://store2:8300,http://store3:8300
      - PROPOSERS=http://proposer1:8000,http://proposer2:8000,http://proposer3:8000,http://proposer4:8000,http://proposer5:8000
    ports:
      - "8003:8000"
    volumes:
      - ./logs:/app/logs
    networks:
      - paxos-network

  proposer4:
    build:
      context: .
      dockerfile: proposer/Dockerfile
    environment:
      - DEBUG=${DEBUG:-false}
      - PROPOSER_ID=proposer_4
      - ACCEPTORS=http://acceptor1:8100,http://acceptor2:8100,http://acceptor3:8100,http://acceptor4:8100,http://acceptor5:8100
      - LEARNERS=http://learner1:8200,http://learner2:8200
      - STORES=http://store1:8300,http://store2:8300,http://store3:8300
      - PROPOSERS=http://proposer1:8000,http://proposer2:8000,http://proposer3:8000,http://proposer4:8000,http://proposer5:8000
    ports:
      - "8004:8000"
    volumes:
      - ./logs:/app/logs
    networks:
      - paxos-network

  proposer5:
    build:
      context: .
      dockerfile: proposer/Dockerfile
    environment:
      - DEBUG=${DEBUG:-false}
      - PROPOSER_ID=proposer_5
      - ACCEPTORS=http://acceptor1:8100,http://acceptor2:8100,http://acceptor3:8100,http://acceptor4:8100,http://acceptor5:8100
      - LEARNERS=http://learner1:8200,http://learner2:8200
      - STORES=http://store1:8300,http://store2:8300,http://store3:8300
      - PROPOSERS=http://proposer1:8000,http://proposer2:8000,http://proposer3:8000,http://proposer4:8000,http://proposer5:8000
    ports:
      - "8005:8000"
    volumes:
      - ./logs:/app/logs
    networks:
      - paxos-network

  # Acceptors
  acceptor1:
    build:
      context: .
      dockerfile: acceptor/Dockerfile
    environment:
      - DEBUG=${DEBUG:-false}
      - ACCEPTOR_ID=acceptor_1
      - LEARNERS=http://learner1:8200,http://learner2:8200
    ports:
      - "8101:8100"
    volumes:
      - ./logs:/app/logs
    networks:
      - paxos-network

  acceptor2:
    build:
      context: .
      dockerfile: acceptor/Dockerfile
    environment:
      - DEBUG=${DEBUG:-false}
      - ACCEPTOR_ID=acceptor_2
      - LEARNERS=http://learner1:8200,http://learner2:8200
    ports:
      - "8102:8100"
    volumes:
      - ./logs:/app/logs
    networks:
      - paxos-network

  acceptor3:
    build:
      context: .
      dockerfile: acceptor/Dockerfile
    environment:
      - DEBUG=${DEBUG:-false}
      - ACCEPTOR_ID=acceptor_3
      - LEARNERS=http://learner1:8200,http://learner2:8200
    ports:
      - "8103:8100"
    volumes:
      - ./logs:/app/logs
    networks:
      - paxos-network

  acceptor4:
    build:
      context: .
      dockerfile: acceptor/Dockerfile
    environment:
      - DEBUG=${DEBUG:-false}
      - ACCEPTOR_ID=acceptor_4
      - LEARNERS=http://learner1:8200,http://learner2:8200
    ports:
      - "8104:8100"
    volumes:
      - ./logs:/app/logs
    networks:
      - paxos-network

  acceptor5:
    build:
      context: .
      dockerfile: acceptor/Dockerfile
    environment:
      - DEBUG=${DEBUG:-false}
      - ACCEPTOR_ID=acceptor_5
      - LEARNERS=http://learner1:8200,http://learner2:8200
    ports:
      - "8105:8100"
    volumes:
      - ./logs:/app/logs
    networks:
      - paxos-network

  # Learners
  learner1:
    build:
      context: .
      dockerfile: learner/Dockerfile
    environment:
      - DEBUG=${DEBUG:-false}
      - LEARNER_ID=learner_1
      - ACCEPTORS=http://acceptor1:8100,http://acceptor2:8100,http://acceptor3:8100,http://acceptor4:8100,http://acceptor5:8100
      - STORES=http://store1:8300,http://store2:8300,http://store3:8300
      - CLIENTS=http://client1:8400,http://client2:8400,http://client3:8400,http://client4:8400,http://client5:8400
    ports:
      - "8201:8200"
    volumes:
      - ./logs:/app/logs
    networks:
      - paxos-network

  learner2:
    build:
      context: .
      dockerfile: learner/Dockerfile
    environment:
      - DEBUG=${DEBUG:-false}
      - LEARNER_ID=learner_2
      - ACCEPTORS=http://acceptor1:8100,http://acceptor2:8100,http://acceptor3:8100,http://acceptor4:8100,http://acceptor5:8100
      - STORES=http://store1:8300,http://store2:8300,http://store3:8300
      - CLIENTS=http://client1:8400,http://client2:8400,http://client3:8400,http://client4:8400,http://client5:8400
    ports:
      - "8202:8200"
    volumes:
      - ./logs:/app/logs
    networks:
      - paxos-network

  # Cluster Stores
  store1:
    build:
      context: .
      dockerfile: cluster_store/Dockerfile
    environment:
      - DEBUG=${DEBUG:-false}
      - STORE_ID=store_1
    ports:
      - "8301:8300"
    volumes:
      - ./data/store1:/app/data
      - ./logs:/app/logs
    networks:
      - paxos-network

  store2:
    build:
      context: .
      dockerfile: cluster_store/Dockerfile
    environment:
      - DEBUG=${DEBUG:-false}
      - STORE_ID=store_2
    ports:
      - "8302:8300"
    volumes:
      - ./data/store2:/app/data
      - ./logs:/app/logs
    networks:
      - paxos-network

  store3:
    build:
      context: .
      dockerfile: cluster_store/Dockerfile
    environment:
      - DEBUG=${DEBUG:-false}
      - STORE_ID=store_3
    ports:
      - "8303:8300"
    volumes:
      - ./data/store3:/app/data
      - ./logs:/app/logs
    networks:
      - paxos-network

  # Clients
  client1:
    build:
      context: .
      dockerfile: client/Dockerfile
    environment:
      - DEBUG=${DEBUG:-false}
      - CLIENT_ID=client_1
      - PROPOSER_URL=http://proposer1:8000
    ports:
      - "8401:8400"  # API port
      - "8501:8500"  # Web UI port
    volumes:
      - ./logs:/app/logs
    networks:
      - paxos-network

  client2:
    build:
      context: .
      dockerfile: client/Dockerfile
    environment:
      - DEBUG=${DEBUG:-false}
      - CLIENT_ID=client_2
      - PROPOSER_URL=http://proposer2:8000
    ports:
      - "8402:8400"  # API port
      - "8502:8500"  # Web UI port
    volumes:
      - ./logs:/app/logs
    networks:
      - paxos-network

  client3:
    build:
      context: .
      dockerfile: client/Dockerfile
    environment:
      - DEBUG=${DEBUG:-false}
      - CLIENT_ID=client_3
      - PROPOSER_URL=http://proposer3:8000
    ports:
      - "8403:8400"  # API port
      - "8503:8500"  # Web UI port
    volumes:
      - ./logs:/app/logs
    networks:
      - paxos-network

  client4:
    build:
      context: .
      dockerfile: client/Dockerfile
    environment:
      - DEBUG=${DEBUG:-false}
      - CLIENT_ID=client_4
      - PROPOSER_URL=http://proposer4:8000
    ports:
      - "8404:8400"  # API port
      - "8504:8500"  # Web UI port
    volumes:
      - ./logs:/app/logs
    networks:
      - paxos-network

  client5:
    build:
      context: .
      dockerfile: client/Dockerfile
    environment:
      - DEBUG=${DEBUG:-false}
      - CLIENT_ID=client_5
      - PROPOSER_URL=http://proposer5:8000
    ports:
      - "8405:8400"  # API port
      - "8505:8500"  # Web UI port
    volumes:
      - ./logs:/app/logs
    networks:
      - paxos-network

networks:
  paxos-network:
    driver: bridge