node:
  id: ${NODE_ID}
  role: proposer
  
paxos:
  quorumSize: ${QUORUM_SIZE}
  batchSize: 10
  batchDelayMs: 50
  proposalTimeout: 2000
  
networking:
  port: 8080
  acceptors:
    - acceptor-1:8080
    - acceptor-2:8080
    - acceptor-3:8080
    - acceptor-4:8080
    - acceptor-5:8080
  learners:
    - learner-1:8080
    - learner-2:8080
    - learner-3:8080
